version: '3.8'

services:
  mysql:
    image: mysql:5.7  # Você pode usar a versão que preferir, como mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '021221' 
      MYSQL_DATABASE: 'sisauth_db'
    ports:
      - '3306:3306'  # Isso mapeia a porta 3306 do contêiner para a porta 3306 na máquina host
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql  # Persiste os dados do MySQL no volume docker

volumes:
  mysql_data:
    driver: local
